In [62]:
import pandas as pd

In [63]:
df = pd.read_csv("datasets/global_volcano_eruption_intelligence.csv")

In [64]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 898 entries, 0 to 897
Data columns (total 77 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   noaa_event_id                      898 non-null    int64
 1   year                               898 non-null    int64
 2   month                              765 non-null    float64
 3   day                                707 non-null    float64
 4   linked_tsunami_event_id            187 non-null    float64
 5   linked_earthquake_event_id         82 non-null     float64
 6   noaa_location_id                   898 non-null    int64
 7   volcanoLocationNewNum              895 non-null    float64
 8   volcanoLocationNum                 898 non-null    str
 9   volcano_name                       898 non-null    str
 10  location_description               898 non-null    str
 11  country                            898 non-null    str
 12  latitude                           898 non-null    float64
 13  longitude                          898 non-null    float64
 14  elevation_m                        898 non-null    int64
 15  volcano_type                       898 non-null    str
 16  eruption_agent_codes               543 non-null    str
 17  deaths_total                       475 non-null    float64
 18  deathsAmountOrderTotal             605 non-null    float64
 19  damage_scale_total                 272 non-null    float64
 20  is_significant                     898 non-null    bool
 21  publish                            898 non-null    bool
 22  is_eruption                        898 non-null    bool
 23  eruption_status                    898 non-null    str
 24  eruption_time_code                 898 non-null    str
 25  vei                                714 non-null    float64
 26  deathsAmountOrder                  578 non-null    float64
 27  damage_scale_direct                250 non-null    float64
 28  housesDestroyedAmountOrderTotal    158 non-null    float64
 29  deaths_direct                      453 non-null    float64
 30  injuries_direct                    106 non-null    float64
 31  injuriesAmountOrder                129 non-null    float64
 32  injuries_total                     110 non-null    float64
 33  injuriesAmountOrderTotal           138 non-null    float64
 34  housesDestroyedAmountOrder         130 non-null    float64
 35  structures_destroyed               52 non-null     float64
 36  structures_destroyed_total         62 non-null     float64
 37  missingAmountOrder                 14 non-null     float64
 38  missingAmountOrderTotal            15 non-null     float64
 39  missing_persons                    12 non-null     float64
 40  missing_persons_total              12 non-null     float64
 41  damage_est_millions_usd            25 non-null     float64
 42  damage_total_millions_usd          29 non-null     float64
 43  tsunami_confirmed                  898 non-null    bool
 44  country_continent                  898 non-null    str
 45  country_region                     898 non-null    str
 46  country_subregion                  897 non-null    str
 47  country_population                 889 non-null    float64
 48  country_area_km2                   889 non-null    float64
 49  data_source                        898 non-null    str
 50  dataset_version                    898 non-null    float64
 51  retrieved_date                     898 non-null    str
 52  build_timestamp                    898 non-null    str
 53  eruption_date                      898 non-null    str
 54  century                            898 non-null    str
 55  decade                             873 non-null    str
 56  era                                898 non-null    str
 57  season_northern_hemisphere         765 non-null    str
 58  vei_category                       898 non-null    str
 59  ejecta_volume_km3_min              714 non-null    float64
 60  energy_release_joules_approx       714 non-null    float64
 61  est_plume_height_km                714 non-null    float64
 62  hemisphere_ns                      898 non-null    str
 63  hemisphere_ew                      898 non-null    str
 64  tectonic_region                    898 non-null    str
 65  ring_of_fire                       898 non-null    bool
 66  island_volcano                     898 non-null    bool
 67  damage_tier                        898 non-null    str
 68  eruption_agent_decoded             543 non-null    str
 69  human_impact_score                 898 non-null    float64
 70  has_casualties                     898 non-null    bool
 71  vei_risk_tier                      898 non-null    str
 72  composite_hazard_score             898 non-null    float64
 73  volcano_eruption_count_in_dataset  898 non-null    int64
 74  avg_eruption_return_period_years   769 non-null    float64
 75  volcano_activity_category          898 non-null    str
 76  row_completeness_pct               898 non-null    float64
dtypes: bool(7), float64(38), int64(5), str(27)
memory usage: 497.4 KB

In [65]:

df.head(20)

,noaa_event_id,year,month,day,linked_tsunami_event_id,linked_earthquake_event_id,noaa_location_id,volcanoLocationNewNum,volcanoLocationNum,volcano_name,...,damage_tier,eruption_agent_decoded,human_impact_score,has_casualties,vei_risk_tier,composite_hazard_score,volcano_eruption_count_in_dataset,avg_eruption_return_period_years,volcano_activity_category,row_completeness_pct
0,5238,-4360,NaN,NaN,NaN,NaN,402021,242021.0,0402-021,Macauley,...,Unknown,NaN,0.0,False,Extreme,45.0,1,NaN,Single Record,100.00
1,4468,-4350,NaN,NaN,NaN,NaN,80206,282060.0,0802-06=,Kikai,...,Unknown,Phreatic / Phreatomagmatic,0.0,False,Catastrophic,52.5,1,NaN,Single Record,100.00
2,5237,-4050,NaN,NaN,NaN,NaN,140410,344100.0,1404-10=,Masaya,...,Unknown,NaN,0.0,False,Extreme,45.0,1,NaN,Single Record,100.00
3,5230,-4000,NaN,NaN,NaN,NaN,50208,252080.0,0502-08=,Witori,...,Unknown,Tsunami Generated,0.0,False,Extreme,45.0,4,1971.3,Moderately Active,100.00
4,5236,-3580,NaN,NaN,NaN,NaN,70307,273070.0,0703-07=,Taal,...,Unknown,NaN,0.0,False,Extreme,45.0,9,700.0,Moderately Active,100.00
5,5228,-3550,NaN,NaN,NaN,NaN,703083,273083.0,0703-083,Pinatubo,...,Unknown,NaN,0.0,False,Extreme,45.0,6,1108.6,Moderately Active,100.00
6,6646,-2420,NaN,NaN,NaN,NaN,10102,211020.0,0101-02=,Vesuvius,...,Unknown,"P,T",0.0,False,Very High,37.5,18,256.7,Frequently Active,100.00
7,5205,-2040,NaN,NaN,NaN,NaN,50105,251050.0,0501-05=,Long Island,...,Unknown,NaN,0.0,False,Extreme,45.0,2,3700.0,Infrequently Active,100.00
8,5235,-1900,NaN,NaN,NaN,NaN,110208,312080.0,1102-08-,Black Peak,...,Unknown,NaN,0.0,False,Extreme,45.0,1,NaN,Single Record,100.00
9,5234,-1890,NaN,NaN,NaN,NaN,1508057,358057.0,1508-057,"Hudson, Cerro",...,Unknown,NaN,0.0,False,Extreme,45.0,4,1293.7,Moderately Active,100.00
10,5233,-1860,NaN,NaN,NaN,NaN,120105,321050.0,1201-05-,St. Helens,...,Unknown,NaN,0.0,False,Extreme,45.0,3,1920.0,Infrequently Active,100.00
11,5232,-1750,NaN,NaN,NaN,NaN,110207,312070.0,1102-07-,Veniaminof,...,Unknown,NaN,0.0,False,Extreme,45.0,1,NaN,Single Record,100.00
12,4645,-1645,NaN,NaN,NaN,NaN,110209,312090.0,1102-09-,Aniakchak,...,Unknown,NaN,0.0,False,Extreme,45.0,1,NaN,Single Record,100.00
13,1351,-1610,NaN,NaN,3.0,5877.0,10204,212040.0,0102-04=,Santorini,...,Unknown,Waves / Surges,0.0,False,Catastrophic,52.5,8,505.1,Moderately Active,100.00
14,5024,-1550,NaN,NaN,NaN,NaN,110303,313030.0,1103-03-,Redoubt,...,Unknown,NaN,0.0,False,Unknown,0.0,2,3559.0,Infrequently Active,83.33
15,5231,-1460,NaN,NaN,NaN,NaN,40107,241070.0,0401-07=,Taupo,...,Unknown,NaN,0.0,False,Extreme,45.0,4,1123.3,Moderately Active,100.00
16,5229,-1370,NaN,NaN,NaN,NaN,50208,252080.0,0502-08=,Witori,...,Unknown,NaN,0.0,False,Extreme,45.0,4,1971.3,Moderately Active,100.00
17,5227,-1050,NaN,NaN,NaN,NaN,703083,273083.0,0703-083,Pinatubo,...,Unknown,NaN,0.0,False,Extreme,45.0,6,1108.6,Moderately Active,100.00
18,6628,-1010,NaN,NaN,NaN,NaN,150208,352080.0,1502-08=,Tungurahua,...,Unknown,NaN,0.0,False,Very High,37.5,11,302.1,Frequently Active,100.00
19,6627,-455,NaN,NaN,NaN,NaN,150205,352050.0,1502-05=,Cotopaxi,...,Unknown,Mudflow / Lahar,0.0,False,High,30.0,6,466.4,Moderately Active,100.00

In [66]:
# Volcano with the most eruption records in the dataset
volcano_counts = df["volcano_name"].value_counts()

print("\nTop 10 volcanoes by record count:")
print(volcano_counts.head(10))

Top 10 volcanoes by record count:
volcano_name
Merapi       28
Etna         25
Semeru       25
Mayon        19
Vesuvius     18
Kelud        18
Asamayama    18
Hekla        16
Asosan       16
Kilauea      16
Name: count, dtype: int64

In [67]:
etna_df = df[df["volcano_name"] == "Etna"].copy().reset_index(drop=True)

# etna_df.to_csv("etna_df1.csv", index=False)
keep_numeric = {"noaa_event_id", "year", "month", "day"}
numeric_cols_to_drop = [
    col for col in etna_df.select_dtypes(include="number").columns
    if col not in keep_numeric
]
etna_df = etna_df.drop(columns=numeric_cols_to_drop)

# etna_df.to_csv("etna_df2.csv", index=False)

In [68]:
from numpy import int8
remaining_etna_df = etna_df[["year", "month", "day", "has_casualties", "vei_category", "vei_risk_tier", "eruption_agent_codes", "eruption_agent_decoded"]].copy().reset_index(drop=True)


remaining_etna_df.dropna(how='any',axis=0, inplace=True) 
remaining_etna_df['month'] = remaining_etna_df['month'].astype(int8)

remaining_etna_df['month'] = pd.to_datetime(remaining_etna_df['month'], format='%m').dt.month_name()
remaining_etna_df.head(30)

,year,month,day,has_casualties,vei_category,vei_risk_tier,eruption_agent_codes,eruption_agent_decoded
1,1169,February,4.0,True,Unknown,Unknown,S,Submarine Eruption
4,1329,July,15.0,False,Severe,Moderate,I,Inundation / Lahar
5,1536,March,26.0,True,Severe,Moderate,T,Tsunami Generated
7,1669,March,19.0,True,Severe,Moderate,L,Lava Flow
9,1832,November,1.0,False,Explosive,Low,L,Lava Flow
10,1843,November,25.0,True,Explosive,Low,L,Lava Flow
12,1928,November,8.0,True,Gentle,Minimal,L,Lava Flow
13,1929,August,2.0,True,Gentle,Minimal,T,Tsunami Generated
14,1979,September,12.0,True,Severe,Moderate,T,Tsunami Generated
16,1984,October,16.0,True,Severe,Moderate,S,Submarine Eruption
17,1985,December,19.0,True,Gentle,Minimal,S,Submarine Eruption
18,1987,April,17.0,True,Explosive,Low,T,Tsunami Generated
23,2017,March,15.0,False,Unknown,Unknown,P,Phreatic / Phreatomagmatic
24,2018,December,26.0,False,Explosive,Low,S,Submarine Eruption

In [69]:
for col in remaining_etna_df.columns:
    # print(f"Attributes: {len(i.columns) - 1}\n")

    print(f"{col}: {remaining_etna_df[col].nunique()} values")
    print(remaining_etna_df[col].unique())
    
remaining_etna_df.drop(columns=["day"], inplace=True)
remaining_etna_df.drop(columns=["eruption_agent_decoded"], inplace=True)

year: 14 values
[1169 1329 1536 1669 1832 1843 1928 1929 1979 1984 1985 1987 2017 2018]
month: 9 values
<StringArray>
[ 'February',      'July',     'March',  'November',    'August', 'September',
   'October',  'December',     'April']
Length: 9, dtype: str
day: 11 values
[ 4. 15. 26. 19.  1. 25.  8.  2. 12. 16. 17.]
has_casualties: 2 values
[ True False]
vei_category: 4 values
<StringArray>
['Unknown', 'Severe', 'Explosive', 'Gentle']
Length: 4, dtype: str
vei_risk_tier: 4 values
<StringArray>
['Unknown', 'Moderate', 'Low', 'Minimal']
Length: 4, dtype: str
eruption_agent_codes: 5 values
<StringArray>
['S', 'I', 'T', 'L', 'P']
Length: 5, dtype: str
eruption_agent_decoded: 5 values
<StringArray>
[        'Submarine Eruption',         'Inundation / Lahar',
          'Tsunami Generated',                  'Lava Flow',
 'Phreatic / Phreatomagmatic']
Length: 5, dtype: str

In [70]:
remaining_etna_df.info()

<class 'pandas.DataFrame'>
Index: 14 entries, 1 to 24
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   year                  14 non-null     int64
 1   month                 14 non-null     str
 2   has_casualties        14 non-null     bool
 3   vei_category          14 non-null     str
 4   vei_risk_tier         14 non-null     str
 5   eruption_agent_codes  14 non-null     str
dtypes: bool(1), int64(1), str(4)
memory usage: 686.0 bytes

In [71]:
MONTH_TO_SEASON = {
    "December": "Winter", "January": "Winter", "February": "Winter",
    "March": "Spring", "April": "Spring", "May": "Spring",
    "June": "Summer", "July": "Summer", "August": "Summer",
    "September": "Autumn", "October": "Autumn", "November": "Autumn",
}

# remaining_etna_df.insert(0, "id", [f"E{i}" for i in range(1, len(remaining_etna_df) + 1)])
remaining_etna_df["month"] = remaining_etna_df["month"].map(MONTH_TO_SEASON)

remaining_etna_df.rename(columns={'month': 'season', 'has_casualties': 'casualties', 'vei_category': 'category', 'vei_risk_tier': 'risk', 'eruption_agent_codes': 'agent'}, inplace=True)

remaining_etna_df.to_csv("datasets/etna_df.csv", index=False)

In [72]:
time_part = remaining_etna_df[["year", "season"]]
time_part.to_csv("datasets/volcano_time_part.csv", index=False)

# time_part_int = remaining_etna_df[["id", "year", "season"]].rename(columns={"season": "month"})
# time_part_int.to_csv("datasets/volcano_time_part_int.csv", index=False)

event_part = remaining_etna_df.drop(columns=["year", "season"])
event_part.to_csv("datasets/volcano_event_part.csv", index=False)

In [73]:
remaining_etna_df = remaining_etna_df.reset_index(drop=True)
remaining_etna_df.insert(0, "id", range(1, len(remaining_etna_df) + 1))

remaining_etna_df.to_csv("datasets/etna_df.csv", index=False)
remaining_etna_df[["id", "year", "season"]].to_csv("datasets/volcano_time_part.csv", index=False)
remaining_etna_df.drop(columns=["year", "season"]).to_csv("datasets/volcano_event_part.csv", index=False)

remaining_etna_df

    id  year  season  casualties   category      risk agent
0    1  1169  Winter        True    Unknown   Unknown     S
1    2  1329  Summer       False     Severe  Moderate     I
2    3  1536  Spring        True     Severe  Moderate     T
3    4  1669  Spring        True     Severe  Moderate     L
4    5  1832  Autumn       False  Explosive       Low     L
5    6  1843  Autumn        True  Explosive       Low     L
6    7  1928  Autumn        True     Gentle   Minimal     L
7    8  1929  Summer        True     Gentle   Minimal     T
8    9  1979  Autumn        True     Severe  Moderate     T
9   10  1984  Autumn        True     Severe  Moderate     S
10  11  1985  Winter        True     Gentle   Minimal     S
11  12  1987  Spring        True  Explosive       Low     T
12  13  2017  Spring       False    Unknown   Unknown     P
13  14  2018  Winter       False  Explosive       Low     S